### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by edmundnoble** [lucidd/scala-js-chrome#15]
I'm curious as to whether or not this project is currently maintained. I need it for edmundnoble/slate, and I have a couple of improvements to PR back to this repo if it is still active. Until then, they're in my fork.

**Comment by lucidd** [comment]
I have been quite bad at maintaining this project for a while but i intend to become more active again.
If you have any requests or enhancements they are very welcome :smile:

**Comment by edmundnoble** [comment]
Excellent thank you. Thanks for 2.12.1 :smiley:
