### ISSUE TITLE
Cannot read property 'onEmbedRequested' of undefined

### ISSUE THREAD

**Issue by darkfrog26** [lucidd/scala-js-chrome#37]
Using the example code here: https://github.com/lucidd/scala-js-chrome#creating-a-basic-window

I get the following error at runtime:

```
main.js:1359 Uncaught TypeError: Cannot read property 'onEmbedRequested' of undefined
    at $c_Lchrome_app_runtime_Runtime$.init___ (main.js:1359)
    at $m_Lchrome_app_runtime_Runtime$ (main.js:1377)
    at $f_Lchrome_utils_ChromeApp__main__V (main.js:1450)
    at $c_Lcom_outr_vrowser_ChromeAppExample$.main__V (main.js:3976)
    at main.js:9562
    at main.js:9563
```

Running against Version 64.0.3282.186 (Official Build) (64-bit) on MacOS.

**Comment by lucidd** [comment]
could it be that you are trying to create a window from an extension instead of an app?

**Comment by darkfrog26** [comment]
Yes, that could be it exactly. :o

It completely avoided notice the distinction between the two until now. Thanks.
