### ISSUE TITLE
chromePackage

### ISSUE THREAD

**Issue by Sergey80** [lucidd/scala-js-chrome#6]
not sure but seems chromePackage not working.
I can not see that task available in sbt console.

**Comment by Roen00** [comment]
Could you provide more information? What error do you have? Could you upload the project configuration which doesn't work?

**Comment by lucidd** [comment]
Could it be that you forgot to enable the plugin for your project? Your `build.sbt` should look something similar to this https://github.com/lucidd/chrome-system-monitor/blob/master/build.sbt.
Also to have the plugin available you have to add it to your `projects/plugins.sbt`
 file. https://github.com/lucidd/chrome-system-monitor/blob/master/project/plugins.sbt

**Comment by Sergey80** [comment]
It simply says that that task does not exist.

**Comment by Sergey80** [comment]
yep. good. thx.
