### ISSUE TITLE
chromePackage takes "content" from the root

### ISSUE THREAD

**Issue by Sergey80** [lucidd/scala-js-chrome#7]
I have multi sbt-project configuration, where myProject aggregates the chrome one

```
  lazy val myProject= Project(id = "myProject", base = file(".")).settings(
    name:="myProject",
    version := Versions.binding
  ).aggregate(chromePlugin, server)
```

so then, commands:
sbt
project chromePlugin
chromePackage

would generate the \unpacked folder with "locales" and "assests" ONLY if I put those "content" folder that contains them outside - to the root of the project like this:

/Main
 /content
 /chromplugin
 /project
- /BuildProject.scala 

But I would expect to put "content" into the "chromplugin" folder and the sbt-plugin would grab proper content

**Comment by lucidd** [comment]
you should be able to work around this by setting `chromePackageContent := ...` manually. But i agree it should pick the content directory from the subprojects root.

**Comment by antonkulaga** [comment]
Is it not possible just to reuse standard resources directories for chromeContent?

**Comment by lucidd** [comment]
@antonkulaga that sounds like a good idea i will try that out.
